name: Delete-Old-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: 删除旧的工作流
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 0
